name: PR Pull

on:
  pull_request:
    types: [opened, reopened, synchronize, labeled]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.generate.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Generate matrix
        id: generate
        run: ./.github/scripts/generate-pr-build-matrix.sh

  build:
    runs-on: ubuntu-latest
    needs:
      - prepare
    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJson(needs.prepare.outputs.matrix) }}
    permissions:
      contents: read
      actions: write
    steps:
      - name: Dispatch PR Build workflow
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh workflow run pr-build.yml --repo ${{ github.repository }} --ref ${{ github.head_ref }} \
            --field target=${{ matrix.target }} \
            --field version=${{ matrix.version }} \
            --field push=${{ contains(github.event.pull_request.labels.*.name, 'pr-pull') }}

  pr-merge:
    if: contains(github.event.pull_request.labels.*.name, 'pr-pull')
    runs-on: ubuntu-latest
    needs:
      - build
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Evaluate the PR for merging
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run:
          gh pr merge --repo ${{ github.repository }} --merge ${{ github.event.pull_request.number }} --delete-branch
