name: release

on:
  workflow_dispatch:
    inputs:
      target:
        type: choice
        description: 'Select target to build'
        required: true
        options:
          - consul
          - openbao
          - vault
      version:
        type: string
        description: 'Specify version to build'
        required: true

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Generate Docker metadata
        id: docker-meta
        uses: docker/metadata-action@v5

      - name: Generate GitHub metadata
        id: github-meta
        uses: dockerbakery/github-metadata-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        env:
          CONSUL_VERSIONS: ${{ inputs.version }}
          VAULT_VERSIONS: ${{ inputs.version }}
          OPENBAO_VERSIONS: ${{ inputs.version }}
        with:
          targets: ${{ inputs.target}}
          push: ${{ github.event_name != 'pull_request' }}
          files: |
            ./docker-bake.hcl
            cwd://${{ steps.docker-meta.outputs.bake-file-labels }}
            cwd://${{ steps.docker-meta.outputs.bake-file-annotations }}
            cwd://${{ steps.github-meta.outputs.bake-file }}
          set: |
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
